# Generated by Django 3.0.7 on 2020-06-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200616_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='geoname_id',
            field=models.IntegerField(default=None),
        ),
    ]
